name: build

on:
  push:
    branches: [ "dev" ]   
  pull_request:
    branches: [ "dev" ]
    
env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use    

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install .NET 8
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui        
      
    - name: Build MReveil
      run: dotnet build "src/MReveil/MReveil.csproj"
