name: build

on:
  push:
    branches: [ "dev" ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'    
  pull_request:
    branches: [ "dev" ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'    
    
env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use    

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
    
    - name: Install .NET workloads
      shell: pwsh
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install maui
      
    - name: Build MReveil
      run: dotnet build "src/MReveil/MReveil.csproj"
