name: publish

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  release:
    types: [created]  # Déclenche lors de la création d'une release

env:
  DOTNET_WORKLOAD: 'maui'  # Le workload à installer

jobs:
  # Job pour Windows
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK (latest)
      uses: actions/setup-dotnet@v3.2.0
      with:
        # Ne spécifie pas de version ici, .NET SDK sera installé en dernière version disponible
        dotnet-version: 'latest'

    - name: Install .NET MAUI Workload
      run: dotnet workload install ${ env.DOTNET_WORKLOAD }

    - name: Build MReveil for Windows
      run: dotnet publish "src/MReveil/MReveil.csproj" -c Release -r win-x64 --self-contained false --output ./publish/windows

  # Job pour macOS
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK (latest)
      uses: actions/setup-dotnet@v3.2.0
      with:
        # Ne spécifie pas de version ici, .NET SDK sera installé en dernière version disponible
        dotnet-version: 'latest'

    - name: Install .NET MAUI Workload
      run: dotnet workload install ${ env.DOTNET_WORKLOAD }

    - name: Build MReveil for macOS
      run: dotnet publish "src/MReveil/MReveil.csproj" -c Release -r osx-x64 --self-contained false --output ./publish/macos

  # Job pour Linux
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK (latest)
      uses: actions/setup-dotnet@v3.2.0
      with:
        # Ne spécifie pas de version ici, .NET SDK sera installé en dernière version disponible
        dotnet-version: 'latest'

    - name: Install .NET MAUI Workload
      run: dotnet workload install ${ env.DOTNET_WORKLOAD }

    - name: Build MReveil for Linux
      run: dotnet publish "src/MReveil/MReveil.csproj" -c Release -r linux-x64 --self-contained false --output ./publish/linux

  # Job pour créer une release GitHub et y ajouter les artefacts
  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]  # Ce job dépend des autres jobs de build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      id: release
      uses: gh actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}  # Utiliser le tag de la release
        release_name: "Release ${{ github.ref }}"
        body: "Release automatique des artefacts"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.MREVEIL_GITHUB_TOKEN }}

    - name: Upload Windows build to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/windows/*
      env:
        GITHUB_TOKEN: ${{ secrets.MREVEIL_GITHUB_TOKEN }}

    - name: Upload macOS build to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/macos/*
      env:
        GITHUB_TOKEN: ${{ secrets.MREVEIL_GITHUB_TOKEN }}

    - name: Upload Linux build to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/linux/*
      env:
        GITHUB_TOKEN: ${{ secrets.MREVEIL_GITHUB_TOKEN }}
